-- HR DB 資料查詢
-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)

-- 1.查詢每個部門的平均薪資
-- 2.查詢高於部門平均薪資的員工

SELECT DEPARTMENT_ID, FLOOR(AVG(SALARY)) "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;


