/*
SQL 練習題(四)
HR DB 資料查詢
查詢每個部門高於平均部門薪資的員工
(結果依部門平均薪資降冪排序)
*/

-- 簡單子查詢
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, 
    D.DEPARTMENT_NAME,
    T_DEP_AVG.DEP_AVG_SALARY
FROM (
	-- 各別部門平均薪資
	SELECT E.DEPARTMENT_ID, FLOOR(AVG(SALARY)) "DEP_AVG_SALARY"
	FROM employees E
	GROUP BY E.DEPARTMENT_ID
) T_DEP_AVG, employees E, departments D
WHERE T_DEP_AVG.DEPARTMENT_ID = E.DEPARTMENT_ID
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY > T_DEP_AVG.DEP_AVG_SALARY
ORDER BY T_DEP_AVG.DEP_AVG_SALARY DESC, E.SALARY DESC;



WITH T_DEP_AVG AS (
	-- 各別部門平均薪資
	SELECT E.DEPARTMENT_ID, FLOOR(AVG(SALARY)) "DEP_AVG_SALARY"
	FROM employees E
	GROUP BY E.DEPARTMENT_ID
)
SELECT T_DEP_AVG.DEPARTMENT_ID, T_DEP_AVG.DEP_AVG_SALARY 
FROM T_DEP_AVG;
