INSERT INTO store_information (STORE_ID, STORE_NAME, SALES, STORE_DATE, GEOGRAPHY_ID)
	VALUES(10, 'AppleInc', 1000, '2023-03-11 00:00:00', 3);
    
SELECT * FROM store_information;

-- 可對交易異動中的資料在資料未提交commit前，進行rollback取消這次交易所有的資料異動指令
ROLLBACK;

-- COMMIT 完成交易作業
-- 如進行資料異動操作後最後須執行交易提交commit的動作資料方可異動成功
-- 交易隔離性：資料庫交易與交易之間彼此獨立，一個交易是看不到另一個交易所異動中的資料
COMMIT;


-- SQL UNION 聯集(不包含重覆值)
-- 1.查詢與查詢之間SELECT的欄位"個數必須相同"
-- 2.查詢與查詢之間SELECT的欄位"型別相同"
-- 1,2,3
SELECT GEOGRAPHY_ID  FROM GEOGRAPHY
UNION
-- NULL,1,2,3
SELECT GEOGRAPHY_ID FROM STORE_INFORMATION;

-- SQL UNION ALL 聯集(包含重覆值)
-- 1,2,3
SELECT GEOGRAPHY_ID  FROM GEOGRAPHY
UNION ALL
-- NULL,1,2,3
SELECT GEOGRAPHY_ID FROM STORE_INFORMATION;

-- SQL INTERSECT 交集
-- MySQL不支援INTERSECT語句
/*
SELECT GEOGRAPHY_ID  FROM GEOGRAPHY
INTERSECT
-- NULL,1,2,3
SELECT GEOGRAPHY_ID FROM STORE_INFORMATION;
*/

-- INNER JOIN + DISTINCT = INTERSECT 查詢交集結果
SELECT DISTINCT G.GEOGRAPHY_ID
FROM GEOGRAPHY G
JOIN STORE_INFORMATION S ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- SQL MINUS 排除(不包含重覆值) 
-- MySQL不支援MINUS語句
/*
-- Oracle
SELECT GEOGRAPHY_ID  FROM GEOGRAPHY
MINUS
SELECT GEOGRAPHY_ID FROM STORE_INFORMATION;

-- MS SQL
SELECT GEOGRAPHY_ID  FROM GEOGRAPHY
EXCEPT
SELECT GEOGRAPHY_ID FROM STORE_INFORMATION;
*/

-- LEFT JOIN + table2.id IS NULL = MINUS
SELECT G.GEOGRAPHY_ID
FROM GEOGRAPHY G
LEFT JOIN STORE_INFORMATION S ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
WHERE S.GEOGRAPHY_ID IS NULL;

-- SQL SubQuery 子查詢

-- 找出營業額最高的商店資料
-- 外查詢
SELECT * 
FROM STORE_INFORMATION
WHERE SALES = (
	-- 內查詢
	SELECT MAX(SALES) FROM STORE_INFORMATION
);

-- 內部查詢本身與外部查詢沒有關係。
-- 這一類的子查詢稱為『簡單子查詢』 (Simple Subquery)
SELECT SUM(SALES)
FROM STORE_INFORMATION
WHERE GEOGRAPHY_ID IN (
	-- 1,2,3
	SELECT GEOGRAPHY_ID FROM GEOGRAPHY
);

-- 內部查詢是要利用到外部查詢提到的表格中的欄位，
-- 那這個字查詢就被稱為『相關子查詢』(Correlated Subquery)
-- 外查詢
SELECT SUM(SALES)
FROM STORE_INFORMATION S
WHERE S.GEOGRAPHY_ID IN (
	-- 內查詢
	SELECT G.GEOGRAPHY_ID FROM GEOGRAPHY G
    WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID
);


-- 『簡單子查詢』 (Simple Subquery)
-- 每個子查詢都可視為一個資料查詢的結果集
-- 查詢與查詢之間"彼此獨立"不能互相使用對方的欄位
SELECT G.*, S.*
FROM (
   SELECT * FROM GEOGRAPHY
) G , 
(
   SELECT * FROM STORE_INFORMATION
) S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


SELECT G.*, S.*
FROM (
   SELECT * FROM GEOGRAPHY
) G , 
(
   SELECT STORE.* 
   FROM STORE_INFORMATION STORE, G
   WHERE STORE.GEOGRAPHY_ID = G.GEOGRAPHY_ID
) S
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;



-- 『相關子查詢』(Correlated Subquery)
WITH G AS (
	SELECT * FROM GEOGRAPHY
),
S AS (
	SELECT * FROM STORE_INFORMATION
)
SELECT G.*, S.* 
FROM G 
JOIN S ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


WITH G AS (
	SELECT * FROM GEOGRAPHY
),
S AS (
	SELECT STORE.* 
    FROM STORE_INFORMATION STORE, G
    WHERE STORE.GEOGRAPHY_ID = G.GEOGRAPHY_ID
)
SELECT S.* FROM S;

-- SQL EXISTS 存在式關聯查詢



-- SQL CASE WHEN 條件查詢

