-- SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY 
SELECT STORE_NAME, SUM(SALES)
FROM store_information
WHERE GEOGRAPHY_ID = 2
GROUP BY STORE_NAME
HAVING SUM(SALES) >= 200
ORDER BY SUM(SALES) ASC;

-- 欄位別名 
-- 1.AS 可省略不寫
-- 2.使用"雙引號"
-- 3."雙引號"可省略不寫
-- 4.別名不可以有空白("雙引號"可以有空白)
SELECT STORE_NAME, SUM(SALES) 加總營業額, COUNT(STORE_ID) "商店數量",
	-- GROUP_CONCAT(STORE_ID ORDER BY STORE_ID DESC SEPARATOR '/'),
	GROUP_CONCAT(SALES ORDER BY STORE_ID DESC SEPARATOR '/') AS "GROUP LIST SUM"
FROM store_information
GROUP BY STORE_NAME;

-- Oracle 群組清單函數
-- SELECT STORE_NAME, SUM(SALES), COUNT(STORE_ID),
-- 	LISTAGG(SALES, ',') WITHIN GROUP (ORDER BY SALES)
-- FROM store_information
-- GROUP BY STORE_NAME;

-- 表格別名.表格欄位 AS "欄位別名"
SELECT S.STORE_ID, S.STORE_NAME AS "商店名稱"
FROM STORE_INFORMATION S;


SELECT G.GEOGRAPHY_ID, G.REGION_NAME,
	S.STORE_ID, S.STORE_NAME, S.SALES, S.GEOGRAPHY_ID, S.STORE_DATE
FROM geography G, STORE_INFORMATION S
-- 表格連接JOIN
WHERE G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


-- INNER JOIN...ON
SELECT G.GEOGRAPHY_ID, G.REGION_NAME,
	S.STORE_ID, S.STORE_NAME, S.SALES, S.GEOGRAPHY_ID, S.STORE_DATE
FROM geography G INNER JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- 左外部連接(LEFT JOIN or LEFT OUTER JOIN)
-- INNER、OUTER 可省略不寫
SELECT G.GEOGRAPHY_ID, G.REGION_NAME,
	S.STORE_ID, S.STORE_NAME, S.SALES, S.GEOGRAPHY_ID, S.STORE_DATE
FROM geography G LEFT JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


SELECT G.GEOGRAPHY_ID, G.REGION_NAME,
	S.STORE_ID, S.STORE_NAME, S.SALES, S.GEOGRAPHY_ID, S.STORE_DATE
FROM geography G RIGHT JOIN STORE_INFORMATION S
ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;

-- PS:MY SQL不支援FULL JOIN
-- SELECT G.GEOGRAPHY_ID, G.REGION_NAME,
-- 	S.STORE_ID, S.STORE_NAME, S.SALES, S.GEOGRAPHY_ID, S.STORE_DATE
-- FROM geography G FULL JOIN STORE_INFORMATION S
-- ON G.GEOGRAPHY_ID = S.GEOGRAPHY_ID;


