SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID ,STORE_NAME, SALES FROM STORE_INFORMATION;

SELECT  STORE_NAME, STORE_ID, SALES FROM STORE_INFORMATION;

SELECT  * FROM STORE_INFORMATION;

-- 表格內的不同資料值
SELECT STORE_NAME FROM STORE_INFORMATION;
