SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID ,STORE_NAME, SALES FROM STORE_INFORMATION;

SELECT  STORE_NAME, STORE_ID, SALES FROM STORE_INFORMATION;

SELECT  * FROM STORE_INFORMATION;

-- 表格內的不同資料值
-- 1.以多欄位整列資料為去重覆的依據
-- 2.DISTINC只能下一次，且必須在所有欄位的最前面
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

SELECT  DISTINCT STORE_ID,  STORE_NAME FROM STORE_INFORMATION;


SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
WHERE SALES >= 1500;

-- AND(且)嚴謹
-- OR(或)寬鬆
SELECT STORE_ID, STORE_NAME, SALES 
FROM STORE_INFORMATION
WHERE SALES > 1000
OR SALES > 275 AND SALES;


SELECT * 
FROM STORE_INFORMATION
WHERE STORE_ID IN (1,2,3);

-- 字串類型的欄位值必須使用'單引號'
SELECT * 
FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Los Angeles', 'Boston');


SELECT * 
FROM STORE_INFORMATION
WHERE SALES >= 700 AND SALES <= 2500;

SELECT * 
FROM STORE_INFORMATION
WHERE SALES BETWEEN 700 AND 2500;