SELECT STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, SALES, STORE_NAME FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION;

-- 欄位資料去重覆
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;

-- 1.以整列資料為去重覆的依據
-- 2.DISTINCT位置只能在欄位的最前面
-- 3.DISTINCT只能下一次
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;
SELECT DISTINCT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION 
WHERE SALES > 1000;

SELECT * FROM STORE_INFORMATION 
WHERE SALES >= 1500;

-- AND(且):條件同時成立
-- OR(或):條件單一成立
SELECT * FROM STORE_INFORMATION
WHERE SALES > 250 AND STORE_DATE > '2018-04-01';

SELECT * FROM STORE_INFORMATION
WHERE SALES <= 300 OR SALES >= 2500;


SELECT * FROM STORE_INFORMATION
WHERE STORE_ID = 1
OR STORE_ID = 2
OR STORE_ID = 3;

SELECT * FROM STORE_INFORMATION
WHERE STORE_ID IN (1,2,3);

SELECT * FROM STORE_INFORMATION
WHERE STORE_NAME IN ('Los Angeles', 'Boston');


SELECT * FROM STORE_INFORMATION
WHERE SALES >= 300 AND SALES <= 2500;

-- BETWEEN ... AND
SELECT * FROM STORE_INFORMATION
WHERE SALES BETWEEN 300 AND 2500;

SELECT * FROM STORE_INFORMATION
WHERE STORE_DATE BETWEEN '2018-02-01' AND '2018-05-30';
