-- SQL 練習題(四)
-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)

SELECT DEP_AVG.*, E.EMPLOYEE_ID, E.FIRST_NAME,  E.SALARY, E.DEPARTMENT_ID
FROM (
	SELECT DEPARTMENT_ID, FLOOR(AVG(SALARY)) DEP_AVG_SALARY
	FROM employees
	GROUP BY DEPARTMENT_ID
) DEP_AVG, employees E
WHERE DEP_AVG.DEPARTMENT_ID = E.DEPARTMENT_ID
AND E.SALARY > DEP_AVG.DEP_AVG_SALARY
ORDER BY E.DEPARTMENT_ID, E.SALARY;
