SELECT STORE_ID, STORE_NAME FROM STORE_INFORMATION;

SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE, GEOGRAPHY_ID, OPEN_STATUS FROM store_information;

SELECT STORE_ID, STORE_NAME, SALES, STORE_DATE, OPEN_STATUS, GEOGRAPHY_ID FROM store_information;

-- DISTINCT 資料去重覆
-- 1.DISTINCT 只能下一次, 所有欄位的最前面
-- 2.DISTINCT 以所有選取的全欄位做去覆
SELECT DISTINCT STORE_NAME FROM STORE_INFORMATION;
SELECT DISTINCT STORE_ID,  STORE_NAME FROM STORE_INFORMATION;
SELECT DISTINCT STORE_NAME, GEOGRAPHY_ID FROM store_information;


SELECT STORE_ID, STORE_NAME, SALES 
FROM store_information 
WHERE SALES >= 1500;

-- AND 而且(嚴謹)
-- OR 或(寬鬆)
SELECT STORE_ID, STORE_NAME, STORE_DATE, SALES
FROM store_information
WHERE STORE_DATE >= '2018-04-01' AND SALES >= 2500;

SELECT STORE_ID, STORE_NAME, STORE_DATE, SALES
FROM store_information
WHERE STORE_DATE >= '2018-04-01' OR SALES <= 300;


SELECT STORE_ID, STORE_NAME, STORE_DATE, SALES
FROM store_information
WHERE STORE_NAME = 'Los Angeles';


SELECT STORE_ID, STORE_NAME, STORE_DATE, SALES
FROM store_information
WHERE STORE_ID = 1 OR STORE_ID = 2 OR STORE_ID = 3;


SELECT STORE_ID, STORE_NAME, STORE_DATE, SALES
FROM store_information
WHERE STORE_ID IN (1,2,3);

SELECT STORE_ID, STORE_NAME, STORE_DATE, SALES
FROM store_information
WHERE STORE_NAME IN ( 'Los Angeles', 'Boston');




